// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Villa 1 Amenity",
                            CreatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5226),
                            Description = "Villa 1 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 1",
                            Occupancy = 4,
                            Rate = 100.0,
                            SquareMeters = 200,
                            UpdatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5282)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Villa 2 Amenity",
                            CreatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5286),
                            Description = "Villa 2 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 2",
                            Occupancy = 6,
                            Rate = 200.0,
                            SquareMeters = 300,
                            UpdatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5287)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Villa 3 Amenity",
                            CreatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5290),
                            Description = "Villa 3 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 3",
                            Occupancy = 8,
                            Rate = 300.0,
                            SquareMeters = 400,
                            UpdatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5291)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Villa 4 Amenity",
                            CreatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5294),
                            Description = "Villa 4 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 4",
                            Occupancy = 10,
                            Rate = 400.0,
                            SquareMeters = 500,
                            UpdatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5295)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Villa 5 Amenity",
                            CreatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5298),
                            Description = "Villa 5 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 5",
                            Occupancy = 12,
                            Rate = 500.0,
                            SquareMeters = 600,
                            UpdatedDate = new DateTime(2024, 11, 2, 13, 6, 7, 801, DateTimeKind.Local).AddTicks(5299)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
